### ISSUE TITLE
Broken Playlists

### ISSUE THREAD

**Issue by aitchFactor** [yoyofr/modizer#35] opened 2019-05-31 00:05 UTC
![6142B43B-A771-42FA-A28A-966766E90F0D](https://user-images.githubusercontent.com/42639410/58672533-c1b37580-838a-11e9-94e1-03cae21ae83b.png)

Playlists currently have multiple issues.

1. Playlist items randomly duplicate when playing playlists, quitting, shuffling playlists or refreshing the app.

2. The “Shuffle & Play” function takes several minutes for large playlists (20+ items) and crashes on extremely large playlists (100+ items).

3. Playlist items can only be removed one at a time from the playlist viewer, and there is a delay caused by deleting each one that seemingly increases proportionally to the number of items in the playlist, up to several seconds. This makes manually deleting duplicates created by issue 1 tedious and difficult.

I really like this app, it’s basically the only music app I use but playlists have had this issue for years now, including multiple updates, without a fix. I hope you read this and make it a priority to rectify these issues.

**Comment by yoyofr** [comment] 2019-06-06 19:28
Hi,

yes, playlists management suffers several bugs in current version. I've
fixed most of them in my current WIP version, I will release it in the
coming weeks

Le ven. 31 mai 2019 à 02:05, aitchFactor <notifications@github.com> a
écrit :

**Comment by aitchFactor** [comment] 2019-09-03 22:05
Thanks for fixing many of these bugs in the latest patch. However playlist items still randomly duplicate in the instances I’ve listed above.

**Comment by yoyofr** [comment] 2019-09-04 05:08
Hi,

I need more details as I did not had duplication issues during my tests.
Please explain all the steps to trigger duplication and I'll fix it.

**Comment by aitchFactor** [comment] 2019-09-04 10:22
[Garou_-_Mark_of_the_Wolves_(Neo_Geo).zip](https://github.com/yoyofr/modizer/files/3574023/Garou_-_Mark_of_the_Wolves_.Neo_Geo.zip)
1. Create a new playlist.
2. Select "Add/Remove files…" and tap the blue » on the file I uploaded.
3. Tap the purple "+ALL" button.
4. Navigate back to the playlists viewer (the screen that lists all the playlists you've created)
5. Tap on the playlist you just created.
6. Some of the files should be duplicated. Some not at all, but others should be duplicated more than once.

**Comment by yoyofr** [comment] 2019-09-09 13:28
Hello

I did follow the  steps and did not have duplicated entries. Can you try to
reset your DB?(it will remove all your playlists and statistics) it is an
option available in the other/maintenance  screen.
I suspect DB corruption issue caused by previous version.

Rgds
ym

Le mer. 4 sept. 2019 à 12:22, aitchFactor <notifications@github.com> a
écrit :

**Comment by aitchFactor** [comment] 2019-09-09 23:42
This seems to have fixed the issue. Thanks for your help.

**Comment by aitchFactor** [comment] 2019-09-10 04:00
Upon further testing it seems it still occurs in some cases. I’m reopening this in case anyone else has the same issue.

**Comment by aitchFactor** [comment] 2019-09-10 04:10
![FF17E14F-26C3-4ACA-9A5F-26DC91642CB3](https://user-images.githubusercontent.com/42639410/64583424-2cd20680-d3d4-11e9-9bfb-e298cd954afc.png)
![3FFD40F7-6F3B-4CDD-AB3C-74836BBA77BC](https://user-images.githubusercontent.com/42639410/64583425-2d6a9d00-d3d4-11e9-9ca9-bb5e50fd519e.png)
![86457131-ED0A-42F0-B962-F7F50507442E](https://user-images.githubusercontent.com/42639410/64583426-2d6a9d00-d3d4-11e9-8366-c13a208bf57d.png)
![3520EAF4-6273-4897-886D-8932567E5312](https://user-images.githubusercontent.com/42639410/64583428-2d6a9d00-d3d4-11e9-95a6-763919ae72cd.jpeg)
After resetting DB and offloading/reinstalling app it seems only the items that play are duplicated. 
Replication steps:
1. Create a playlist. 
2. Tap on a song in the playlist in the playlist viewer.
3. Navigate back to the playlists viewer (select the back arrow twice)
4. Tap on the playlist again. The item previously selected should be the only one duplicated.

**Comment by aitchFactor** [comment] 2019-09-10 04:22
![7C527A35-AB87-47B8-BACF-431F998866FD](https://user-images.githubusercontent.com/42639410/64583959-6b68c080-d3d6-11e9-8140-11688b4fa652.gif)

**Comment by yoyofr** [comment] 2019-09-11 14:48
Hi,

Ok thanks, I will fix this in next version.

Le mar. 10 sept. 2019 à 06:22, aitchFactor <notifications@github.com> a
écrit :

**Comment by yoyofr** [comment] 2021-02-16 09:34
should be fixed in v2.9.4

**Closed by yoyofr** 2021-02-16 09:34 UTC
